// the code is generated by the generator script at ./generate.py
import "ace-builds/src-noconflict/mode-typescript";
import "ace-builds/src-noconflict/snippets/typescript";
import { ReactNode } from "react";

export interface IndexProps {
  children: ReactNode;
}
export default function index(props: IndexProps) {
  return <>{props.children}</>;
}
